name: CI

on:
  push:
    branches: [main]
  pull_request_target:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm install

      - name: Print PR title
        run: |
          echo "Building PR titled ${{ github.event.pull_request.title }}"

      - run: npm test

      - uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true
